export const home = {
    GET_ALL_TAGS: 'GET_ALL_TAGS',
    TAGS_LOAD_SUCCESS: 'TAGS_LOAD_SUCCESS',
    FETCH_ADS: 'FETCH_ADS',
}

export const details = {
    USER_SEARCH: 'USER_SEARCH',
    GET_AD: 'GET_AD',
    CREATE_AD: 'CREATE_AD',
    CHANGE_AD: 'CHANGE_AD',
}

export const shared = {
    UPDATE_FIELD: 'UPDATE_FIELD',
    REDIRECT: 'REDIRECT',
    ERROR: 'ERROR',
}

export const auth = {
    SIGNUP_USER: 'SIGNUP_USER',
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
}

export const messaging = {
    UPDATE_MESSAGE_HISTORY: 'UPDATE_MESSAGE_HISTORY',
    CLIENT_ID: 'CLIENT_ID',
    MESSAGE_TYPE: 'MESSAGE_TYPE',
    SET_CONNECTION_STATUS: 'SET_CONNECTION_STATUS',
}